// Mocks generated by Mockito 5.1.0 from annotations
// in dicoding_mfde_submission/test/presentation/pages/movie/top_rated_movies_page_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:dicoding_mfde_submission/common/state_enum.dart' as _i4;
import 'package:dicoding_mfde_submission/domain/entities/movie_tv_show.dart'
    as _i5;
import 'package:dicoding_mfde_submission/domain/usecases/get_top_rated.dart'
    as _i2;
import 'package:dicoding_mfde_submission/presentation/provider/top_rated_notifier.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeGetTopRated_0 extends _i1.Fake implements _i2.GetTopRated {}

/// A class which mocks [TopRatedNotifier].
///
/// See the documentation for Mockito's code generation for more information.
class MockTopRatedNotifier extends _i1.Mock implements _i3.TopRatedNotifier {
  MockTopRatedNotifier() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetTopRated get getTopRated =>
      (super.noSuchMethod(Invocation.getter(#getTopRated),
          returnValue: _FakeGetTopRated_0()) as _i2.GetTopRated);
  @override
  _i4.RequestState get state => (super.noSuchMethod(Invocation.getter(#state),
      returnValue: _i4.RequestState.empty) as _i4.RequestState);
  @override
  List<_i5.MovieTvShow> get movies =>
      (super.noSuchMethod(Invocation.getter(#movies),
          returnValue: <_i5.MovieTvShow>[]) as List<_i5.MovieTvShow>);
  @override
  String get message =>
      (super.noSuchMethod(Invocation.getter(#message), returnValue: '')
          as String);
  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);
  @override
  _i6.Future<void> fetchTopRated(String? type) =>
      (super.noSuchMethod(Invocation.method(#fetchTopRated, [type]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i6.Future<void>);
  @override
  void addListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#addListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void removeListener(_i7.VoidCallback? listener) =>
      super.noSuchMethod(Invocation.method(#removeListener, [listener]),
          returnValueForMissingStub: null);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void notifyListeners() =>
      super.noSuchMethod(Invocation.method(#notifyListeners, []),
          returnValueForMissingStub: null);
}
